version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: php:7.1-apache
        environment:
          APP_ENV: test
    steps:
      - checkout
      - run:
          name: Install system packages
          command: apt-get update && apt-get -y install zip git zlib1g-dev wget
      - run:
          name: Install PHP extensions
          command: |
            docker-php-ext-install pdo
            docker-php-ext-install zip
            docker-php-xdebug
      - run:
          name: Display PHP information
          command: |
            php -v
      - run:
          name: Check PHP sintax
          command: find . -name \*.php -exec php -l "{}" \;
      - run:
          name: Run PHPUnit
          command: vendor/bin/phpunit
      - persist_to_workspace:
          root: /
          paths:
            - app
workflows:
  version: 2
  build_publish_deploy:
    jobs:
      - build
      - publish:
          context: DockerRegistry
          requires:
            - build